# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'kellywaters@gmail.com'
  config.password       = 'Iginla12'
  config.integrator_key = 'DEVE-f7536494-2395-4b8a-9073-f033cc6330b9'
  config.account_id     = '1124786'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

