development:
  adapter: postgresql
  encoding: unicode
  database: noa_canada_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: noa_canada_test
  pool: 5
  username: kellywaters
  password: 